### ISSUE TITLE
Clicking too fast in the main menu causes react infinite update error

### ISSUE THREAD

**Issue by maximiliancsuk** [max-bytes/omnikeeper#255]
```
react-dom.development.js:27292 Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (react-dom.development.js:27292:1)
    at scheduleUpdateOnFiber (react-dom.development.js:25475:1)
    at dispatchSetState (react-dom.development.js:17527:1)
    at onVisibleChange (Menu.js:368:1)
    at updateDisplayCount (Overflow.js:151:1)
    at Overflow.js:220:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitLayoutEffectOnFiber (react-dom.development.js:23268:1)
    at commitLayoutMountEffects_complete (react-dom.development.js:24688:1)
    at commitLayoutEffects_begin (react-dom.development.js:24674:1)
checkForNestedUpdates @ react-dom.development.js:27292
scheduleUpdateOnFiber @ react-dom.development.js:25475
dispatchSetState @ react-dom.development.js:17527
onVisibleChange @ Menu.js:368
updateDisplayCount @ Overflow.js:151
(anonymous) @ Overflow.js:220
commitHookEffectListMount @ react-dom.development.js:23150
commitLayoutEffectOnFiber @ react-dom.development.js:23268
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25651
react_devtools_backend.js:4026 The above error occurred in the <Overflow> component:

    at Overflow (http://localhost:3000/static/js/bundle.js:402650:32)
    at InheritableContextProvider (http://localhost:3000/static/js/bundle.js:399629:23)
    at Menu (http://localhost:3000/static/js/bundle.js:398255:32)
    at InternalMenu (http://localhost:3000/static/js/bundle.js:272714:90)
    at Menu (http://localhost:3000/static/js/bundle.js:272815:90)
    at Route (http://localhost:3000/static/js/bundle.js:503895:29)
    at header
    at Basic (http://localhost:3000/static/js/bundle.js:271227:25)
    at Adapter (http://localhost:3000/static/js/bundle.js:271210:66)
    at section
    at BasicLayout (http://localhost:3000/static/js/bundle.js:271242:63)
    at Adapter (http://localhost:3000/static/js/bundle.js:271210:66)
    at LayerSettingsContextProvider (http://localhost:3000/static/js/bundle.js:1497:134)
    at Router (http://localhost:3000/static/js/bundle.js:503526:30)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:503147:35)
    at BR (http://localhost:3000/static/js/bundle.js:1526:104)
    at ApolloProvider (http://localhost:3000/static/js/bundle.js:649732:19)
    at ApolloProvider (http://localhost:3000/static/js/bundle.js:649732:19)
    at ApolloWrapper (http://localhost:3000/static/js/bundle.js:2244:16)
    at KeycloakProvider (http://localhost:3000/static/js/bundle.js:110437:47)
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
overrideMethod @ react_devtools_backend.js:4026
logCapturedError @ react-dom.development.js:18687
update.callback @ react-dom.development.js:18720
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23391
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25651
react-dom.development.js:27292 Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (react-dom.development.js:27292:1)
    at scheduleUpdateOnFiber (react-dom.development.js:25475:1)
    at dispatchSetState (react-dom.development.js:17527:1)
    at onVisibleChange (Menu.js:368:1)
    at updateDisplayCount (Overflow.js:151:1)
    at Overflow.js:220:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitLayoutEffectOnFiber (react-dom.development.js:23268:1)
    at commitLayoutMountEffects_complete (react-dom.development.js:24688:1)
    at commitLayoutEffects_begin (react-dom.development.js:24674:1)
checkForNestedUpdates @ react-dom.development.js:27292
scheduleUpdateOnFiber @ react-dom.development.js:25475
dispatchSetState @ react-dom.development.js:17527
onVisibleChange @ Menu.js:368
updateDisplayCount @ Overflow.js:151
(anonymous) @ Overflow.js:220
commitHookEffectListMount @ react-dom.development.js:23150
commitLayoutEffectOnFiber @ react-dom.development.js:23268
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25651
```

**Comment by maximiliancsuk** [comment]
Hopefully fixed by antd upgrade to 4.22.4
